# Generated by Django 3.2.4 on 2021-07-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_number_accumulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='accumulated',
            field=models.IntegerField(),
        ),
    ]
