# Generated by Django 3.2.4 on 2021-07-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_number_accumulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
